version: '3'


services:
    django:
        build: .
        command: >
            sh -c "
            python manage.py makemigrations --noinput && python manage.py migrate --noinput &&
            python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - .env
        networks:
            - some_network
    db:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        env_file:
            - .env
        networks:
            - some_network


networks:
    some_network:
        driver: bridge

volumes:
    postgres_data: