# Generated by Django 4.2.7 on 2024-04-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passinformation',
            options={'verbose_name': 'Pass Info'},
        ),
    ]
