# Generated by Django 4.2.7 on 2024-04-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passinformation',
            name='json_name',
        ),
        migrations.AddField(
            model_name='pass',
            name='json_name',
            field=models.CharField(choices=[('coupon', 'Coupon'), ('eventTicket', 'Event'), ('generic', 'Generic'), ('storeCard', 'Storecard')], default='', verbose_name='Name pass'),
        ),
    ]
