# Generated by Django 4.2.7 on 2024-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0002_remove_pass_pass_information_pass_pass_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='suppressStripShine',
            field=models.BooleanField(default=None, verbose_name='Suppress Strip Shine'),
        ),
    ]
