# Generated by Django 4.2.7 on 2024-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0003_alter_pass_suppressstripshine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='suppressStripShine',
            field=models.BooleanField(blank=True, default=None, verbose_name='Suppress Strip Shine'),
        ),
    ]
