# Generated by Django 4.2.7 on 2024-04-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0003_field_date_style_field_number_style_field_time_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='change_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Change Message'),
        ),
    ]
