# Generated by Django 4.2.7 on 2024-04-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0004_alter_field_change_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text'),
        ),
    ]
