# Generated by Django 4.2.7 on 2024-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0005_alter_barcode_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('imagefile', models.FileField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='pass',
            name='files',
            field=models.ManyToManyField(related_name='images', to='pass_app.images'),
        ),
    ]
