# Generated by Django 4.2.7 on 2024-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0005_alter_pass_suppressstripshine'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='expirationDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expire Date'),
        ),
    ]
